version: '3.1'

networks:
  app-tier:
    external: true

services:
  kafka-0-s:
    image: apache/kafka:latest
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0-s:9093
      - KAFKA_KRAFT_CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # for docker internal network
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0-s:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT


    volumes:
      - kafka_0_data_s:/kafka/data

  kafka-ui-s:
    image: "provectuslabs/kafka-ui:latest"
    networks:
      - app-tier
    container_name: "kafka-ui-s"
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=wizard_test
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0-s:9092
    depends_on:
      - kafka-0-s

  kafka-producer:
    build:
      context: ../..          
      dockerfile: infrastructure/docker/Dockerfile.data_ingestion
    networks:
      - app-tier
    depends_on:
      - kafka-0-s

volumes:
  kafka_0_data_s:
    driver: local