version: '3.1'

networks:
  app-tier:
    external: true

services:
  kafka-0-s:
    image: apache/kafka:latest
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0-s:9093
      - KAFKA_KRAFT_CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # for docker internal network
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0-s:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Additional settings for schema registry compatibility
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka_0_data_s:/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka-ui-s:
    image: "provectuslabs/kafka-ui:latest"
    networks:
      - app-tier
    container_name: "kafka-ui-s"
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=wizard_test
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0-s:9092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
    depends_on:
      kafka-0-s:
        condition: service_healthy

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    networks:
      - app-tier
    container_name: schema-registry
    ports:
      - "9081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka-0-s:9092
    depends_on:
      kafka-0-s:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  kafka-producer:
    build:
      context: ../..          
      dockerfile: infrastructure/docker/Dockerfile.data_ingestion
    networks:
      - app-tier    
    depends_on:
      kafka-0-s:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      
volumes:
  kafka_0_data_s:
    driver: local