dataset:
  name: "cloud_gaming"
  path: "ml/data/simulated_4k_cloud_gaming_dataset.csv"
  target_column: "QoE_score"
  features:
    - "CPU_usage"
    - "GPU_usage"
    - "Bandwidth_MBps"
    - "Latency_ms"
    - "FrameRate_fps"
    - "Jitter_ms"

model:
  output_dir: "ml/models/"
  output_name: "cloud_gaming_model.pkl"
  test_size: 0.2
  random_state: 42

models_to_train:
  - name: "linreg"
    type: "LinearRegression"
    params: {}
  
  - name: "elasticnet"
    type: "ElasticNet"
    params:
      alpha: 0.1
      l1_ratio: 0.5
  
  - name: "random_forest"
    type: "RandomForestRegressor"
    params:
      n_estimators: 300
      max_depth: 15
      min_samples_leaf: 5
      random_state: 42
      n_jobs: -1
  
  - name: "gradient_boosting"
    type: "GradientBoostingRegressor"
    params:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 4
      random_state: 42